# Use an official Postgres as a parent image
FROM postgres:12

# Set the working directory to /app
WORKDIR /postgres

# Copy the current directory contents into the container at /app
COPY . /postgres


# Start the Postgres db server when the container launches
CMD 

